add test results checker to ci

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -726,7 +726,6 @@ jobs:
         run: find ./website/build
 
   check-docker-limit-after:
-    if: needs.determine-tests-based-off-commit.outputs.e2e == 'true'
     needs: [
       e2e-k8s-v2-encrypted-tests,
       e2e-external-storage-tests,
@@ -752,19 +751,58 @@ jobs:
     uses: terascope/workflows/.github/workflows/check-github-api-limit.yml@main
     secrets: inherit
 
+  tests-result-checker:
+    needs:
+      [
+        linux-unit-tests,
+        e2e-k8s-v2-encrypted-tests,
+        e2e-external-storage-tests,
+        e2e-k8s-v2-tests,
+        e2e-tests,
+        elasticsearch-api-tests,
+        elasticsearch-store-tests,
+        teraslice-elasticsearch-tests,
+        lint-and-sync,
+        test-website
+      ]
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check job results
+        run: |
+          failed=""
+
+          declare -A results
+          results["linux-unit-tests"]="${{ needs.linux-unit-tests.result }}"
+          results["e2e-k8s-v2-encrypted-tests"]="${{ needs.e2e-k8s-v2-encrypted-tests.result }}"
+          results["e2e-external-storage-tests"]="${{ needs.e2e-external-storage-tests.result }}"
+          results["e2e-k8s-v2-tests"]="${{ needs.e2e-k8s-v2-tests.result }}"
+          results["e2e-tests"]="${{ needs.e2e-tests.result }}"
+          results["elasticsearch-api-tests"]="${{ needs.elasticsearch-api-tests.result }}"
+          results["elasticsearch-store-tests"]="${{ needs.elasticsearch-store-tests.result }}"
+          results["teraslice-elasticsearch-tests"]="${{ needs.teraslice-elasticsearch-tests.result }}"
+          results["lint-and-sync"]="${{ needs.lint-and-sync.result }}"
+          results["test-website"]="${{ needs.test-website.result }}"
+
+          for job in "${!results[@]}"; do
+            result="${results[$job]}"
+            echo "$job: $result"
+            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
+              failed+="$job ($result)\n"
+            fi
+          done
+
+          if [[ -n "$failed" ]]; then
+            echo -e "::error::Some jobs failed or were cancelled:\n$failed"
+            exit 1
+          fi
+
+          echo "All required jobs passed or were skipped."
+
+
+
   all-tests-passed:
-    needs: [
-      linux-unit-tests,
-      e2e-k8s-v2-encrypted-tests,
-      e2e-external-storage-tests,
-      e2e-k8s-v2-tests,
-      e2e-tests,
-      elasticsearch-api-tests,
-      elasticsearch-store-tests,
-      teraslice-elasticsearch-tests,
-      lint-and-sync,
-      test-website
-    ]
+    needs: [tests-result-checker]
     runs-on: ubuntu-latest
     steps:
       - run: echo "All tests have passed"
