remove all tests passed ci job

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1166,57 +1166,57 @@ jobs:
     uses: terascope/workflows/.github/workflows/check-github-api-limit.yml@pnpm
     secrets: inherit
 
-  all-tests-passed:
-    needs:
-      [
-        # linux-unit-tests,
-        build-dev-docker-images,
-        e2e-k8s-v2-encrypted-tests,
-        # e2e-external-asset-storage-tests,
-        # e2e-external-asset-storage-tests-encrypted,
-        e2e-k8s-v2-tests,
-        # e2e-tests,
-        # elasticsearch-api-tests,
-        # elasticsearch-store-tests,
-        # teraslice-elasticsearch-tests,
-        # xlucene-translator-tests,
-        lint-and-sync,
-        # test-website,
-        determine-tests-based-off-commit
-      ]
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check job results
-        run: |
-          failed=""
+  # all-tests-passed:
+  #   needs:
+  #     [
+  #       # linux-unit-tests,
+  #       build-dev-docker-images,
+  #       e2e-k8s-v2-encrypted-tests,
+  #       # e2e-external-asset-storage-tests,
+  #       # e2e-external-asset-storage-tests-encrypted,
+  #       e2e-k8s-v2-tests,
+  #       # e2e-tests,
+  #       # elasticsearch-api-tests,
+  #       # elasticsearch-store-tests,
+  #       # teraslice-elasticsearch-tests,
+  #       # xlucene-translator-tests,
+  #       lint-and-sync,
+  #       # test-website,
+  #       determine-tests-based-off-commit
+  #     ]
+  #   if: always()
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Check job results
+  #       run: |
+  #         failed=""
 
-          declare -A results
-          results["linux-unit-tests"]="${{ needs.linux-unit-tests.result }}"
-          results["xlucene-translator-tests"]="${{ needs.xlucene-translator-tests.result }}"
-          results["e2e-k8s-v2-encrypted-tests"]="${{ needs.e2e-k8s-v2-encrypted-tests.result }}"
-          results["e2e-external-asset-storage-tests"]="${{ needs.e2e-external-asset-storage-tests.result }}"
-          results["e2e-external-asset-storage-tests-encrypted"]="${{ needs.e2e-external-asset-storage-tests-encrypted.result }}"
-          results["e2e-k8s-v2-tests"]="${{ needs.e2e-k8s-v2-tests.result }}"
-          results["e2e-tests"]="${{ needs.e2e-tests.result }}"
-          results["elasticsearch-api-tests"]="${{ needs.elasticsearch-api-tests.result }}"
-          results["elasticsearch-store-tests"]="${{ needs.elasticsearch-store-tests.result }}"
-          results["teraslice-elasticsearch-tests"]="${{ needs.teraslice-elasticsearch-tests.result }}"
-          results["lint-and-sync"]="${{ needs.lint-and-sync.result }}"
-          results["test-website"]="${{ needs.test-website.result }}"
-          results["determine-tests-based-off-commit"]="${{needs.determine-tests-based-off-commit.result}}"
+  #         declare -A results
+  #         results["linux-unit-tests"]="${{ needs.linux-unit-tests.result }}"
+  #         results["xlucene-translator-tests"]="${{ needs.xlucene-translator-tests.result }}"
+  #         results["e2e-k8s-v2-encrypted-tests"]="${{ needs.e2e-k8s-v2-encrypted-tests.result }}"
+  #         results["e2e-external-asset-storage-tests"]="${{ needs.e2e-external-asset-storage-tests.result }}"
+  #         results["e2e-external-asset-storage-tests-encrypted"]="${{ needs.e2e-external-asset-storage-tests-encrypted.result }}"
+  #         results["e2e-k8s-v2-tests"]="${{ needs.e2e-k8s-v2-tests.result }}"
+  #         results["e2e-tests"]="${{ needs.e2e-tests.result }}"
+  #         results["elasticsearch-api-tests"]="${{ needs.elasticsearch-api-tests.result }}"
+  #         results["elasticsearch-store-tests"]="${{ needs.elasticsearch-store-tests.result }}"
+  #         results["teraslice-elasticsearch-tests"]="${{ needs.teraslice-elasticsearch-tests.result }}"
+  #         results["lint-and-sync"]="${{ needs.lint-and-sync.result }}"
+  #         results["test-website"]="${{ needs.test-website.result }}"
+  #         results["determine-tests-based-off-commit"]="${{needs.determine-tests-based-off-commit.result}}"
 
-          for job in "${!results[@]}"; do
-            result="${results[$job]}"
-            echo "$job: $result"
-            if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
-              failed+="$job ($result)\n"
-            fi
-          done
+  #         for job in "${!results[@]}"; do
+  #           result="${results[$job]}"
+  #           echo "$job: $result"
+  #           if [[ "$result" == "failure" || "$result" == "cancelled" ]]; then
+  #             failed+="$job ($result)\n"
+  #           fi
+  #         done
 
-          if [[ -n "$failed" ]]; then
-            echo -e "::error::Some jobs failed or were cancelled:\n$failed"
-            exit 1
-          fi
+  #         if [[ -n "$failed" ]]; then
+  #           echo -e "::error::Some jobs failed or were cancelled:\n$failed"
+  #           exit 1
+  #         fi
 
-          echo "All required jobs passed or were skipped."
+  #         echo "All required jobs passed or were skipped."
